# -*- coding: utf-8 -*-
"""EMSNO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uRiTxDycM57mxoogPLFLYfrszw37LC4H
"""

import cv2
from google.colab.patches import cv2_imshow

img=cv2.imread("/content/red.png")
cv2.waitKey()
cv2.destroyAllWindows()

img.shape

img[100,100]

B,G,R= img[100,100]

B

G

R

def calc(B,G,R):
  if(B>145 and B>182):
    if(G>18 and G>105):
     if(R<256 and R>245):
      print("High")
  
  if(B>145 and B<182):
    if(G>18 and G<105):
      if(R<256 and R>245):
        print("Medium")
  else:
    print("Low")

if(B>132 and B<204):
  if(G>19 and G<193):
    if(R>198 and R<256):
      print("You uploaded a valid pink color.")
      calc(B,G,R)

else:
  print("Not a valid pink color.")